### ISSUE TITLE
Please add a license file and a readme

### ISSUE THREAD

**Issue by unixorn** [DrgnFireYellow/notenote#1]
I'd like to add this to [awesome-zsh-plugins](https://github.com/unixorn/awesome-zsh-plugins), but I prefer to add plugins with a readme so that users can tell what features they provide.

Also, please add a license file, some people won't use any code that doesn't have an open source license. If you don't have one in mind, https://choosealicense.com is a good resource to help you select an appropriate one.

Thanks!

**Comment by DrgnFireYellow** [comment]
Sorry for the slow response, but I'll start on that right away!

**Comment by DrgnFireYellow** [comment]
I am very excited to have my work on the Awesome ZSH list. I hope you will take a second look at the project. Thank you!
